httpService:
  minReplicas: 2
  maxReplicas: 10

restservice:
  name: restservice
  serviceType: ClusterIP
  serviceName: restservice
  image: restservice:latest
  replicaCount: 2
  containerPort: 3000
  servicePort: 80
  pullPolicy: Never

wsservice:
  name: wsservice
  serviceType: ClusterIP
  serviceName: wsservice
  replicaCount: 3
  image: wsservice:latest
  containerPort: 8080
  servicePort: 80
  pullPolicy: Never

zookeeper:
  name: zookeeper
  serviceName: zookeeper
  image: confluentinc/cp-zookeeper:7.4.0
  replicas: 1
  servicePort: 2181

kafka:
  name: kafka
  serviceName: kafka
  image: confluentinc/cp-kafka:7.4.0
  replicas: 1
  servicePort: 9092
  zookeeperConnect: zookeeper:2181