httpService:
  minReplicas: 1
  maxReplicas: 10

restservice:
  name: restservice
  serviceType: ClusterIP
  serviceName: restservice
  image: restservice:latest
  replicaCount: 1
  containerPort: 3000
  servicePort: 81
  pullPolicy: Never

wsservice:
  name: wsservice
  serviceType: ClusterIP
  serviceName: wsservice
  replicaCount: 1
  image: wsservice:latest
  containerPort: 8080
  servicePort: 80
  pullPolicy: Never

kafka:
  name: kafka
  serviceName: kafka
  image: bitnami/kafka:latest
  replicas: 1
  servicePort: 9092
  env:
    KAFKA_KRAFT_MODE: "true"
    KAFKA_CFG_PROCESS_ROLES: "broker,controller"
    KAFKA_CFG_NODE_ID: "1"
    KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
    KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
    KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
    KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    KAFKA_CFG_LOG_DIRS: "/bitnami/kafka/data"
    KAFKA_LOG4J_LOGGERS: "kafka.controller=DEBUG,kafka.producer=DEBUG,kafka.network=DEBUG,kafka.server=DEBUG,kafka.request.logger=DEBUG,state.change.logger=TRACE"