httpService:
  minReplicas: 2
  maxReplicas: 10

rest:
  name: rest
  serviceType: ClusterIP
  serviceName: http-service
  image: rest-api:latest
  replicaCount: 2
  containerPort: 3000
  servicePort: 80
  pullPolicy: Never

kafka:
  name: kafka
  serviceType: ClusterIP
  serviceName: kafka-service
  replicaCount: 3
  image: kafka-consumer:latest
  containerPort: 8080
  servicePort: 81
  pullPolicy: Never