apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
      - name: {{ .Values.kafka.name }}
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: {{ .Values.kafka.servicePort }}
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "{{ .Values.kafka.zookeeperConnect }}"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:{{ .Values.kafka.servicePort }}"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LOG4J_LOGGERS
          value: "kafka.controller=DEBUG,kafka.producer=DEBUG,kafka.network=DEBUG,kafka.server=DEBUG,kafka.request.logger=DEBUG,state.change.logger=TRACE"