apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rest.name }}
spec:
  replicas: {{ .Values.rest.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.rest.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rest.name }}
    spec:
      containers:
        - name: {{ .Values.rest.name }}
          image: {{ .Values.rest.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.rest.containerPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
        - name: {{ .Values.kafka.name }}
          image: {{ .Values.kafka.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.kafka.containerPort }}
