apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: notification.local
    http:
      paths:
      - path: /rest
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.restservice.serviceName }}  # Matches values.yaml
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.restservice.serviceName }} # This must match `kubectl get svc`
            port:
              number: 80
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.wsservice.serviceName }} # This must match `kubectl get svc`
            port:
              number: 80
