apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rest.serviceName }}
spec:
  type: {{ .Values.rest.serviceType }}  # This uses the value from values.yml
  selector:
    app: {{ .Values.rest.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.rest.servicePort }}
      targetPort: {{ .Values.rest.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.serviceName }}
spec:
  type: {{ .Values.kafka.serviceType }}  # This uses the value from values.yml
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.servicePort }}
      targetPort: {{ .Values.kafka.containerPort }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours, adjust as needed
