apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.restservice.serviceName }}
spec:
  type: {{ .Values.restservice.serviceType }}  # This uses the value from values.yml
  selector:
    app: {{ .Values.restservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.restservice.servicePort }}
      targetPort: {{ .Values.restservice.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.wsservice.serviceName }}
spec:
  type: {{ .Values.wsservice.serviceType }}  # This uses the value from values.yml
  selector:
    app: {{ .Values.wsservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.wsservice.servicePort }}
      targetPort: {{ .Values.wsservice.containerPort }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours, adjust as needed
---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.serviceName }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.zookeeper.servicePort }}
      targetPort: {{ .Values.zookeeper.servicePort }}
  selector:
    app: {{ .Values.zookeeper.serviceName }}

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.serviceName }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.servicePort }}
      targetPort: {{ .Values.kafka.servicePort }}
  selector:
    app: {{ .Values.kafka.serviceName }}