apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer  # Match the label from the Deployment
  ports:
    - protocol: TCP
      port: 8080  # Port on which the service will be accessible
      targetPort: 8080  # Port on which your app is running inside the container
      nodePort: 30080  
  type: NodePort  # Use LoadBalancer for external access (use ClusterIP for internal)